name: Pipeline
on:
 push:
  branches: ["master"]
jobs:
  build:
   name: Minha primeira pipeline  
   runs-on: ubuntu-latest
   steps:     
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x
      - name: Checkout do código
        uses: actions/checkout@v2 
      - name: Execução do teste de integração da API com container
        run: dotnet test ./test/CadastroAnimeSerie.API.Test
      - name: Publicando a API
        run: dotnet publish ./src/CadastroAnimeSerie.API